network: linear
exploration_wrapper:
  _partial_: True
  _target_: torchrl.modules.tensordict_module.exploration.AdditiveGaussianWrapper
  sigma_init: 1.0
  sigma_end: 0.1
  annealing_num_steps: ${collector.total_frames}
  action_key: "action"
  spec: null
  safe: True
