defaults:
  - collector: sync_single
  - env: cartpole
  - collection_env: parallel
  - transforms: pixels
  - replay_buffer: circular
  - model: dqn/distributional
  - network: dqn/pixels
  - exploration: linear
  - loss: dqn_loss
  - logger: csv
num_workers: 0
